src/chaincode.hpp
src/extendedprivatekey.hpp
src/extendedpublickey.hpp

Currently in Dash, we use just one BLS key. This is probably fine for everything we've done up until this point, however going into the future, it'll become more important that we are using derived keys. This is for a couple of reasons:
1. It'll allow us to share a dedicated privatekey with Platform and other services that may want to be able to sign messages directly with the operator BLS key. Currently this is not possible because it would compromise ChainLocks and InstantSend security
2. It is generally good cryptographic process to use derived keys where possible. Sometimes attacks exist where an attacker with a large amount of cipertext or ciphertext/plaintext pairs can calculate a privatekey based on the ciphertexts / plaintexts and public key

Preparation for using Extended keys

---

README.md

~~Based on #6 + it points to the status of `develop` which we don't have at the time of PR opening.~~

readme: Fix and expand build status

---

.github/workflows/bls-signatures.yml
go-bindings/aggregationinfo.cpp
go-bindings/aggregationinfo.go
go-bindings/blschia.cpp
go-bindings/chaincode.cpp
go-bindings/chaincode.go
go-bindings/extendedprivatekey.cpp
go-bindings/extendedprivatekey.go
go-bindings/extendedpublickey.cpp
go-bindings/extendedpublickey.go
go-bindings/privatekey.cpp
go-bindings/privatekey.go
go-bindings/publickey.cpp
go-bindings/publickey.go
go-bindings/signature.cpp
go-bindings/signature.go

They are not required if the BLS library is installed but instead they just lead to unexpected behaviour in some cases where the bindings are used out of the repo's folder structure or if the library in there hasn't been compiled (which IMO shouldn't be an precondition to only use the bindings?).

go-bindings|github: Drop relative paths in LDFLAGS and CXXFLAGS + Adjust include paths

---

python-bindings/pythonbindings.cpp
src/CMakeLists.txt
src/bls.hpp
src/elements.cpp
src/elements.hpp
src/legacy.cpp
src/legacy.hpp
src/privatekey.cpp
src/privatekey.hpp
src/schemes.cpp
src/schemes.hpp
src/test.cpp
src/threshold.cpp
src/threshold.hpp

Some notes:
- The new library version has a whole new structure. What we had before in `publickey.hpp/.cpp` and `signatures.hpp/.cpp` files is now in `element.hpp/.cpp` where `G1Element` represents a public key and `G2Element` represents a signature in the (yet) only available `MPL` (Minimum pubkey length) schemes which can be found in `schemes.hpp/.cpp` (Thats the file were the signing/verification schemes defined in the standard draft are implemented by using the available primitives).
- `LegacySchemeMPL` in `schemes.hpp/.cpp` is the scheme i added to represents the signing/verification from our latest release https://github.com/dashpay/bls-signatures/releases/tag/v20181101 to make it compatible with previous dash core versions.
- I integrated all changes required for threshold fun from …

src|python: Add legacy and threshold support

---

src/privatekey.cpp
src/privatekey.hpp
src/test.cpp

On iOS many of our unit tests were using this function, when it was removed in the update it made a lot of tests fail. It's far easier to add it here then rewrite the tests a different way.

feat: added back in private keys from BIP32 Seed

---

src/threshold.cpp

This template is defined in `<memory>`, but it was not included.
Somehow this was not causing problems with older versions of GCC, probably because it was transitively included by something else.
However, this caused an error with GCC 12 that is stricter in this regard.

Fix missing include for std::unique_ptr

---

.github/workflows/build-test.yaml
go-bindings/Makefile
go-bindings/elements.go
go-bindings/privatekey.go
go-bindings/schemes.go
go-bindings/threshold.go
go-bindings/util.go

To prevent releasing allocated memory, we have to use `runtime.KeepAlive` function to inform GC about it
This PR adds `runtime.KeepAlive` calls, to ensure memory is consistent

refactor: use runtime.KeepAlive to prevent GC memory release

---

src/threshold.cpp

The header <memory> should be included explicitly.

fix: build with ubuntu 22.10 (gcc 12) due to missing header

---

configure.ac

macOS Ventura causes the GMP test suite to fail, which in turn causes the library to behave erratically. Until such errata are rectified upstream by libgmp, we have automatic backend selection pick the easy backend if targeting macOS on Apple Silicon.

build: disable gmp if targeting darwin on aarch64 when on 'auto'

---

.gitignore
configure.ac

`relic_conf.h` generates preprocessor definitions that conflict with `bitcoin-config.h` and certain global variables within Dash Core. Some of these definitions can be removed by eliminating some definitions ([source](https://www.gnu.org/software/automake/manual/html_node/List-of-Automake-options.html)) and the rest can be eliminated by substitution. We are using in-place substitution with a `.old` to accommodate for BSD sed (used on macOS, FreeBSD and other BSDs)

build: reduce config macro conflicts, improve documentation, set valid version number

---

src/elements.cpp
src/test.cpp

Fixes an issue introduced in https://github.com/dashpay/bls-signatures/pull/44/commits/ffd1622aede13d1a44e179406caf19d4b04b9b9d via #44 (dropped `if` while moving from https://github.com/dashpay/bls-signatures/pull/44/commits/ffd1622aede13d1a44e179406caf19d4b04b9b9d#diff-f486cfa221391360bf21a00b48ddd8c47fc27116db3454e782e3e942d9b5b45bR83 to https://github.com/dashpay/bls-signatures/pull/44/commits/ffd1622aede13d1a44e179406caf19d4b04b9b9d#diff-f486cfa221391360bf21a00b48ddd8c47fc27116db3454e782e3e942d9b5b45bR26).
Should fix https://github.com/dashpay/dash/pull/5077#issuecomment-1339201568 (I reindexed on testnet with this patch applied on top of develop and had no issues).

fix: Should not check validity for legacy G1 and G2 in FromBytes

---

include/dashbls/bls.hpp
src/bls.cpp
src/elements.cpp

This PR protects the library from staying in a invalid state when trying to unserialize data encoded in basic BLS scheme in legacy.
This fix basically resets Relic library and avoids throwing an exception on such case.

fix: Reinit Relic lib while processing basic data in legacy mode.

---

include/dashbls/elements.hpp
rust-bindings/bls-dash-sys/bindings.rs
rust-bindings/bls-dash-sys/c-bindings/elements.cpp
rust-bindings/bls-dash-sys/c-bindings/elements.h
rust-bindings/bls-signatures/src/elements.rs
src/elements.cpp

extend it out to bindings as well

feat: implement memory-copy only of G1Element and G2Element

---

configure.ac

It resolves: https://github.com/dashpay/dash/issues/5270
It is still workaround but it should be more reliable.

fix: dash is no more pretending being a 'libdashbls'

---

rust-bindings/bls-signatures/Cargo.toml
rust-bindings/bls-signatures/src/elements.rs
rust-bindings/bls-signatures/src/private_key.rs

Implement Debug trait for G1Element, G2Element and PrivateKey with entity data hex output

feat: debug with data hex

---

rust-bindings/bls-dash-sys/build.rs

Make changes to build.rs to support android builds.

fix: support android

---

configure.ac

"ARCH=ARM" is for ARM 32-bit architecture only
https://github.com/dashpay/bls-signatures/blob/develop/depends/relic/cmake/arch.cmake#L6

fix: aarch64 is not supported, should set ARCH to RELIC_NONE

---

configure.ac

[bls-signatures#52](https://github.com/dashpay/bls-signatures/pull/52) was merged in due to a bug in libgmp ([source](https://gmplib.org/list-archives/gmp-bugs/2022-November/005217.html)) that resulted in erratic behavior certain macOS environments. This has since been resolved with GMP 6.3.0 ([source](https://gmplib.org/gmp6.3)) and is available with Homebrew ([source](https://github.com/Homebrew/homebrew-core/blob/51c899140c84d38dfa4c4fe623c859e6241504a0/Formula/g/gmp.rb#L5)).  Ubuntu 20.04 (`focal`) distributes GMP 6.2.0 ([source](https://packages.ubuntu.com/focal/libgmp-dev)) and Debian 11 (`bullseye`) distributes GMP 6.2.1 ([source](https://packages.debian.org/search?suite=bullseye&arch=any&searchon=names&keywords=libgmp-dev)) and these versions work fine with `dashbls` in their …

build: enforce minimum versions of libgmp based on arch and platform

---

apple.rust.deps.sh

CI in `dash-shared-core` repo that compiles `bls_signatures` is failing because GMP project [has banned](https://www.theregister.com/2023/06/28/microsofts_github_gmp_project/) the GitHub Actions/Azure ranges.
To bypass this, this PR changes the source of download to some other location, e.g. https://ftp.gnu.org/gnu/gmp/

chore: change of gmp source

---

python-bindings/CMakeLists.txt

For some reason, building, only inside of dash core, on asahi linux (aarch64 16k page size running on m1 mac pro) failing with errors like:
```
-- pybind11 v2.10.0 
CMake Error at build/_deps/pybind11-src/tools/pybind11NewTools.cmake:189 (python3_add_library):
Unknown CMake command "python3_add_library".
Call Stack (most recent call first):
src/dashbls/python-bindings/CMakeLists.txt:16 (pybind11_add_module)
```
when I bump to 2.13.6 it solves this. Really not sure why

refactor: bump pybind version to 2.13.6

---

configure.ac

Resolves `configure` script not working in FreeBSD (reported in https://github.com/dashpay/dash/issues/6343) due to `bash`-isms introduced in [bls-signatures#85](https://github.com/dashpay/bls-signatures/pull/85.)
* Linux reports AMD64 `$host_cpu` as `x86_64` but FreeBSD reports it as `amd64`, the current detection case doesn't account for that, resulting in FreeBSD builds using the fallback "unspecified 64-bit CPU". This has been resolved.
* `BUILD_`{`BENCH`, `TEST`} are unused and serve no purpose, they have been removed (the conditional `USE`_{`BENCH`, `TEST`} are used instead).

build: replace `bash`-isms with `sh`-friendly `test` and `case`, cleanup

---

.github/workflows/build-binds.yml

* GitHub Actions has refused to work with Python 3.7 on `macos-latest` (14.7), using an `arm64` runner ([build](https://github.com/dashpay/bls-signatures/actions/runs/12151711341/job/33886798487#step:3:50))
* Python 3.7 was declared EoL in June 2023 as was 3.8 in October 2024 ([source](https://devguide.python.org/versions/)). It has instead been replaced with Python 3.12 (shipped with Ubuntu 24.04 `noble`, [source](https://packages.ubuntu.com/noble/python3))
* Python 3.13 currently doesn't work with bindings ([build](https://github.com/dashpay/bls-signatures/actions/runs/12158184297/job/33905556985?pr=103#step:11:956))
* Go 1.12 was EoL in Aug 2022 ([source](https://endoflife.date/go)), replaced with lowest supported Go version, 1.22

ci: drop EoL Python 3.7 and 3.8, Go 1.17, replace with Python 3.12, Go 1.22

---

configure.ac

Noticed that gmp couldn't be detected on FreeBSD while testing #102. This patch should fix it.

fix: gmp detection on FreeBSD

---

include/dashbls/elements.hpp
include/dashbls/privatekey.hpp
src/elements.cpp
src/privatekey.cpp

This builds on top of #74 to enhance library performance when integrated into other stuff

feat: serialize on the stack

---

src/test-bench.cpp

Add serialization benchmarks, use BasicSchemeMPL in existing benchmarks, drop irrelevant ones
<details>
<summary>Results (m1 pro)</summary>
```
Signing
Total: 5000 runs in 3835 ms
Avg: 0.767 ms
Verification
Total: 1000 runs in 2527 ms
Avg: 2.527 ms
Batch verification preparation
Total: 10000 runs in 8786 ms
Avg: 0.8786 ms
Public key validation
Total: 10000 runs in 1896 ms
Avg: 0.1896 ms
Signature validation
Total: 10000 runs in 2048 ms
Avg: 0.2048 ms
Aggregation
Total: 10000 runs in 20 ms
Avg: 0.002 ms
Batch verification
Total: 10000 runs in 11056 ms
Avg: 1.1056 ms
Serialize PrivateKey
Total: 5000000 runs in 134 ms
Avg: 2.68e-05 ms
Serialize G1Element
Total: 5000000 runs in 1036 ms
Avg: 0.0002072 ms
Serialize G2Element
Total: 5000000 runs in 1541 ms
Avg: 0.0003082 ms
SerializeToArray …
```

bench: make benchmarks a bit more useful

---

configure.ac

* Depends on https://github.com/dashpay/bls-signatures/pull/106
* Version slated to include [bls-signatures#75](https://github.com/dashpay/bls-signatures/pull/75) and [bls-signatures#106](https://github.com/dashpay/bls-signatures/pull/106)

chore: bump version to 1.3.5
